name: fast_barcode_scanner
description: A fast barcode scanner using MLKit on Android and AVFoundation on iOS.
version: 2.0.0-dev.5
#remove this before we publish
publish_to: none
homepage: https://github.com/jhoogstraat/fast_barcode_scanner
repository: https://github.com/jhoogstraat/fast_barcode_scanner

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  fast_barcode_scanner_platform_interface: ^2.0.0-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.jhoogstraat.fast_barcode_scanner
        pluginClass: FastBarcodeScannerPlugin
      ios:
        pluginClass: FastBarcodeScannerPlugin
